### ISSUE TITLE
Enhanced monitoring in DD for RDS Postgres

### ISSUE THREAD

**Issue by stancy007** [DataDog/dd-aws-lambda-functions#32]
Hi team,
I want to implement 'Enhanced monitoring of RDS Postgres in DD'.
I see that your script is created for "engine": "Aurora".
https://github.com/DataDog/dd-aws-lambda-functions/tree/master/rds_enhanced_monitoring

Can I replace the engine with RDS and deploy this script?

Regards,
SA

**Comment by garnermccloud** [comment]
Hi @stancy007 - this script is compatible with each db engine including Postgres automatically, so no need to replace anything in the code. See here for the parsing implementation:
https://github.com/DataDog/dd-aws-lambda-functions/blob/master/rds_enhanced_monitoring/lambda_function.py#L26

Regards,
Garner
