### ISSUE TITLE
Possible typo in lambda?

### ISSUE THREAD

**Issue by apurva-sharma** [DataDog/dd-aws-lambda-functions#34]
https://github.com/DataDog/dd-aws-lambda-functions/blob/master/Log/lambda_function.py#L45
Should this not be 
if ddApiKey != "<your_api_key>" or ddApiKey == "":
instead of:
if ddApiKey == "<your_api_key>" or ddApiKey == "":

**Comment by NBParis** [comment]
Hello @apurva-sharma ,

Thanks for your feedback.
The idea of this test is to raise an exception if the api key has not been changed or filled.

Therefore we do verify that `<your_api_key>` that we set by default has been changed and the attribute is not empty.

Let me know if that clarify the situation.
Thanks,
Nils

**Comment by apurva-sharma** [comment]
Makes sense, I interpreted it as fail the job if the apikey is set to any value OTHER than one's api-key.
Thanks for the clarification.
