### ISSUE TITLE
Please update the Readme

### ISSUE THREAD

**Issue by oviliz** [DataDog/dd-aws-lambda-functions#36]
Could you please update the Readme to reflect the current Lambda interface/features?

For instance, I can't find the #Parameters anywhere as this is the whole code of the lambda_function.py:
```
def lambda_handler(event, context):
    # TODO implement
    return 'Hello from Lambda'
```

**Comment by oviliz** [comment]
Actually, I'm confused now. I've been brought to https://github.com/DataDog/dd-aws-lambda-functions/tree/master/Log from the **Collect Logs** tab into https://app.datadoghq.com/account/settings#integrations/amazon_web_services but I see that this is not the Readme page.

**Comment by NBParis** [comment]
Hello @oviliz ,

Thanks for reaching out.
#Parameters can be found here: https://github.com/DataDog/dd-aws-lambda-functions/blob/master/Log/lambda_function.py#L20

Is this what you were looking for?
Let me know if I misunderstood the issue.

Thanks,
Nils
