### ISSUE TITLE
[RDS] Add custom RDS tags on RDS metrics

### ISSUE THREAD

**Issue by tmichelet** [DataDog/dd-aws-lambda-functions#5]
We currently send the RDS enhanced metrics with a few tags (`dbinstanceidentifier` being the identifier). This is a problem because people could have RDS instances with the same identifier over different regions. In that case, the resulting metrics would be an aggregation of the metrics of both instances.

A quick fix for that would be to add `instanceResourceId` as a tag, as this may be unique.

However, a better solution would be to have the `endpoint` accessible in the payload, as the endpoint is currently used as the unique identifier of a RDS instance within datadog. If we had access to it, we could link these metrics with the RDS hosts within datadog, and add all the custom tags.

Another way would be to have the `instanceResourceId` available via regular RDS api, to use this as the unique identifier instead of the endpoint.

**Comment by NBParis** [comment]
Discussed with Tristan.
Old issue and not relevant anymore.

Closing.
