### ISSUE TITLE
Lambda timeout logs should be treated as errors

### ISSUE THREAD

**Issue by qoomon** [DataDog/dd-aws-lambda-functions#55]
If a lambda function runs in a timeout it logs a message like this
`2018-08-26T02:13:13.948Z 3364d63a-b18c-5ed6-97c7-85c6bf57800e Task timed out after 30.02 seconds`

Unfortunately there is no `Error` word in this log so it's not possible to set `status` field to `Error` by just parsing with grok.

I came up with the following workaround, you may want to include something like this in the default lambda log integration pipeline

**Step One**
add  a **Grok Parser** to create a new field called `error_message`
```
lambda_timeout_rule  %{date("yyyy-MM-dd'T'HH:mm:ss.SSSZ"):timestamp}\s+%{notSpace:lambda.request_id}\s+%{regex("Task timed out .*"):error_message}
```

**Step Two**
add a **Category Processor** to set the `status` field to `Error` if an `error_message` field is present

*Review added entries*
Name: `ERROR`
MATCHING QUERY: `@error_message:*`

**Comment by NBParis** [comment]
Hello @qoomon thanks again for the suggestion and help.

We had indeed never faced a timeout in a Lambda function which would explain why this was not covered.
Moreover the recommendation to use the Category Processor to set the `status` is indeed the best option in such cases.

We can definitely improve the default lambda integration with this as well.
Do you know if the format is always the same or if the timeout time can have different format (ms, s, minutes, ...) and would it be relevant to extract it as well?

**Comment by qoomon** [comment]
Hi,
yes the format is the same for all time outs I tested this a loot at my current projekt wie 5k parallel lambda functions for transforming images. 
For now Grok Parser and Category Processor setup works without any error.

**Comment by qoomon** [comment]
Thank you so much.
